#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x5E408CD91CD839D2 (bugzilla@tut.by)
#
Name     : indent
Version  : 2.2.12
Release  : 9
URL      : http://mirrors.kernel.org/gnu/indent/indent-2.2.12.tar.gz
Source0  : http://mirrors.kernel.org/gnu/indent/indent-2.2.12.tar.gz
Source1  : http://mirrors.kernel.org/gnu/indent/indent-2.2.12.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: indent-bin = %{version}-%{release}
Requires: indent-info = %{version}-%{release}
Requires: indent-license = %{version}-%{release}
Requires: indent-locales = %{version}-%{release}
Requires: indent-man = %{version}-%{release}
BuildRequires : autoconf-archive-dev
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : bison
BuildRequires : gettext-bin
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : m4
BuildRequires : pkg-config-dev
BuildRequires : texinfo
Patch1: 0001-Make-sure-doc-dvi-ps-pdf-html-dir-options-to-configu.patch

%description
============================
GNU indent changes the appearance of a C program by inserting or
deleting whitespace according to a plethora of options.  Some
canned styles of formatting are supported as well.  GNU indent is
a descendant of BSD indent.  This file is part of the GNU indent
distribution.

%package bin
Summary: bin components for the indent package.
Group: Binaries
Requires: indent-license = %{version}-%{release}

%description bin
bin components for the indent package.


%package doc
Summary: doc components for the indent package.
Group: Documentation
Requires: indent-man = %{version}-%{release}
Requires: indent-info = %{version}-%{release}

%description doc
doc components for the indent package.


%package info
Summary: info components for the indent package.
Group: Default

%description info
info components for the indent package.


%package license
Summary: license components for the indent package.
Group: Default

%description license
license components for the indent package.


%package locales
Summary: locales components for the indent package.
Group: Default

%description locales
locales components for the indent package.


%package man
Summary: man components for the indent package.
Group: Default

%description man
man components for the indent package.


%prep
%setup -q -n indent-2.2.12
cd %{_builddir}/indent-2.2.12
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1632204003
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1632204003
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/indent
cp %{_builddir}/indent-2.2.12/COPYING %{buildroot}/usr/share/package-licenses/indent/8624bcdae55baeef00cd11d5dfcfa60f68710a02
%make_install
%find_lang indent

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/indent

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/indent/*

%files info
%defattr(0644,root,root,0755)
/usr/share/info/indent.info

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/indent/8624bcdae55baeef00cd11d5dfcfa60f68710a02

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/indent.1

%files locales -f indent.lang
%defattr(-,root,root,-)

